#!/usr/bin/env bash

output=$(git pull --rebase origin main 2>&1)

if [[ "${output}" =~ "Already up to date" ]]; then
    # no output
    :
else
    # Adds all stdout and stderr output to the screen
    echo "${output}"
fi

git add -A

